# Assigns distances to pre set objects based off training set

import constants

KNOWN_OBJECT_HEIGHTS = {
    "person": constants.OBJECT_HEIGHT_PERSON_MM,
    "bicycle": constants.OBJECT_HEIGHT_BICYCLE_MM,
    "car": constants.OBJECT_HEIGHT_CAR_MM,
    "motorcycle": constants.OBJECT_HEIGHT_MOTORCYCLE_MM,
    "airplane": constants.OBJECT_HEIGHT_AIRPLANE_MM,
    "bus": constants.OBJECT_HEIGHT_BUS_MM,
    "train": constants.OBJECT_HEIGHT_TRAIN_MM,
    "truck": constants.OBJECT_HEIGHT_TRUCK_MM,
    "boat": constants.OBJECT_HEIGHT_BOAT_MM,
    "traffic light": constants.OBJECT_HEIGHT_TRAFFIC_LIGHT_MM,
    "fire hydrant": constants.OBJECT_HEIGHT_FIRE_HYDRANT_MM,
    "stop sign": constants.OBJECT_HEIGHT_STOP_SIGN_MM,
    "parking meter": constants.OBJECT_HEIGHT_PARKING_METER_MM,
    "bench": constants.OBJECT_HEIGHT_BENCH_MM,
    "bird": constants.OBJECT_HEIGHT_BIRD_MM,
    "cat": constants.OBJECT_HEIGHT_CAT_MM,
    "dog": constants.OBJECT_HEIGHT_DOG_MM,
    "horse": constants.OBJECT_HEIGHT_HORSE_MM,
    "sheep": constants.OBJECT_HEIGHT_SHEEP_MM,
    "cow": constants.OBJECT_HEIGHT_COW_MM,
    "elephant": constants.OBJECT_HEIGHT_ELEPHANT_MM,
    "bear": constants.OBJECT_HEIGHT_BEAR_MM,
    "zebra": constants.OBJECT_HEIGHT_ZEBRA_MM,
    "giraffe": constants.OBJECT_HEIGHT_GIRAFFE_MM,
    "backpack": constants.OBJECT_HEIGHT_BACKPACK_MM,
    "umbrella": constants.OBJECT_HEIGHT_UMBRELLA_MM,
    "handbag": constants.OBJECT_HEIGHT_HANDBAG_MM,
    "tie": constants.OBJECT_HEIGHT_TIE_MM,
    "suitcase": constants.OBJECT_HEIGHT_SUITCASE_MM,
    "frisbee": constants.OBJECT_HEIGHT_FRISBEE_MM,
    "skis": constants.OBJECT_HEIGHT_SKIS_MM,
    "snowboard": constants.OBJECT_HEIGHT_SNOWBOARD_MM,
    "sports ball": constants.OBJECT_HEIGHT_SPORTS_BALL_MM,
    "kite": constants.OBJECT_HEIGHT_KITE_MM,
    "baseball bat": constants.OBJECT_HEIGHT_BASEBALL_BAT_MM,
    "baseball glove": constants.OBJECT_HEIGHT_BASEBALL_GLOVE_MM,
    "skateboard": constants.OBJECT_HEIGHT_SKATEBOARD_MM,
    "surfboard": constants.OBJECT_HEIGHT_SURFBOARD_MM,
    "tennis racket": constants.OBJECT_HEIGHT_TENNIS_RACKET_MM,
    "bottle": constants.OBJECT_HEIGHT_BOTTLE_MM,
    "wine glass": constants.OBJECT_HEIGHT_WINE_GLASS_MM,
    "cup": constants.OBJECT_HEIGHT_CUP_MM,
    "fork": constants.OBJECT_HEIGHT_FORK_MM,
    "knife": constants.OBJECT_HEIGHT_KNIFE_MM,
    "spoon": constants.OBJECT_HEIGHT_SPOON_MM,
    "bowl": constants.OBJECT_HEIGHT_BOWL_MM,
    "banana": constants.OBJECT_HEIGHT_BANANA_MM,
    "apple": constants.OBJECT_HEIGHT_APPLE_MM,
    "sandwich": constants.OBJECT_HEIGHT_SANDWICH_MM,
    "orange": constants.OBJECT_HEIGHT_ORANGE_MM,
    "broccoli": constants.OBJECT_HEIGHT_BROCCOLI_MM,
    "carrot": constants.OBJECT_HEIGHT_CARROT_MM,
    "hot dog": constants.OBJECT_HEIGHT_HOT_DOG_MM,
    "pizza": constants.OBJECT_HEIGHT_PIZZA_MM,
    "donut": constants.OBJECT_HEIGHT_DONUT_MM,
    "cake": constants.OBJECT_HEIGHT_CAKE_MM,
    "chair": constants.OBJECT_HEIGHT_CHAIR_MM,
    "couch": constants.OBJECT_HEIGHT_COUCH_MM,
    "potted plant": constants.OBJECT_HEIGHT_POTTED_PLANT_MM,
    "bed": constants.OBJECT_HEIGHT_BED_MM,
    "dining table": constants.OBJECT_HEIGHT_DINING_TABLE_MM,
    "toilet": constants.OBJECT_HEIGHT_TOILET_MM,
    "tv": constants.OBJECT_HEIGHT_TV_MM,
    "laptop": constants.OBJECT_HEIGHT_LAPTOP_MM,
    "mouse": constants.OBJECT_HEIGHT_MOUSE_MM,
    "remote": constants.OBJECT_HEIGHT_REMOTE_MM,
    "keyboard": constants.OBJECT_HEIGHT_KEYBOARD_MM,
    "cell phone": constants.OBJECT_HEIGHT_CELL_PHONE_MM,
    "microwave": constants.OBJECT_HEIGHT_MICROWAVE_MM,
    "oven": constants.OBJECT_HEIGHT_OVEN_MM,
    "toaster": constants.OBJECT_HEIGHT_TOASTER_MM,
    "sink": constants.OBJECT_HEIGHT_SINK_MM,
    "refrigerator": constants.OBJECT_HEIGHT_REFRIGERATOR_MM,
    "book": constants.OBJECT_HEIGHT_BOOK_MM,
    "clock": constants.OBJECT_HEIGHT_CLOCK_MM,
    "vase": constants.OBJECT_HEIGHT_VASE_MM,
    "scissors": constants.OBJECT_HEIGHT_SCISSORS_MM,
    "teddy bear": constants.OBJECT_HEIGHT_TEDDY_BEAR_MM,
    "hair drier": constants.OBJECT_HEIGHT_HAIR_DRIER_MM,
    "toothbrush": constants.OBJECT_HEIGHT_TOOTHBRUSH_MM,
    "default": constants.DEFAULT_OBJECT_HEIGHT_MM,
}


def estimate_distance_from_bbox(detection):
    real_height = KNOWN_OBJECT_HEIGHTS.get(detection.class_name, KNOWN_OBJECT_HEIGHTS["default"])
    pixel_height = max(detection.height, 1)
    return (real_height * constants.CAMERA_FOCAL_PX) / pixel_height


def attach_distances(detections):
    for det in detections:
        det.distance_mm = estimate_distance_from_bbox(det)
    return detections
